<?php
/**
 * Description: Read files created by branchhours script and 
 *          output to file with Monday-Sunday hours listing.
 * Arguments: 
 *    input directory path of files generated by branchhours
 *    name of branch - This will prefix to output file
 *    output directory path 
 *
 * Returns: Nothing. outputs contents to file in output path specified. 
 * 
 */
 
date_default_timezone_set('America/Toronto');

if (count($argv) != 4 ) {
   echo "Usage: hours_concat-2.php <input_directory_path> <branch> <output_directory_path>";
   exit;
}

$output_filename = $argv[2] . "_library_hours.html";
isset($argv[1]) ? $input_directory = $argv[1] : $input_directory = "/var/www/hours/";
isset($argv[3]) ? $output_directory = $argv[3] : $output_directory = "/var/www/hours/";
 
$output_content = " <h3><i class='icon-time'></i> Hours of Operation</h3>\n";

$output_content .= "<ul>\n";
$output_file = $output_directory . "/" . $output_filename; //e.g. /path/to/dir/library_hours.html

$monday_time = strtotime('monday this week');
$monday_date = date("Ymd", $monday_time);

for ($i=0; $i < 7; $i++) {

   $next_day = 60*60*24 * $i;
   $date = date("Ymd", $monday_time + $next_day);
   $file = $input_directory . "/" . $date . ".html"; //e.g. 20130806.html

   if (!file_exists($file)) {
      $convert_to_time = strtotime($date);
      $name_of_day = date("D", $convert_to_time);
      $output_content .= "<li> <span class='day'>$name_of_day</span><span class='hours'>Hours Unavailable" . "</span></li>\n";      
   }else {
      $output_content .= trim(file_get_contents($file)) . "\n";
   }    

}
$output_content .= "</ul>\n";
print_r($output_content);

file_put_contents($output_file, $output_content);
?>